"""empty message

Revision ID: 088908ea51a6
Revises: dad98b0f54bb
Create Date: 2016-01-10 17:04:38.962961

"""

# revision identifiers, used by Alembic.
revision = '088908ea51a6'
down_revision = 'dad98b0f54bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=45), nullable=True),
    sa.Column('description', sa.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'post', sa.Column('id_post_type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'post_type', ['id_post_type'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column(u'post', 'id_post_type')
    op.drop_table('post_type')
    ### end Alembic commands ###
